import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'fr' | 'it' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navbar
    'nav.home': 'INICIO',
    'nav.about': 'QUIÉNES SOMOS',
    'nav.services': 'SERVICIOS',
    'nav.scanner': 'ESCÁNER',
    'nav.contact': 'CONTACTO',
    'nav.freeConsultation': 'CONSULTA GRATIS',
    
    // Hero
    'hero.title': 'SOLUCIONES DE CIBERSEGURIDAD PARA SU EMPRESA',
    'hero.subtitle': 'Cyberlabforensics especializada en ofrecer soluciones de ciberseguridad. Protegemos eficazmente los activos digitales de nuestros clientes.',
    'hero.knowUs': 'CONÓCENOS',
    'hero.contact': 'CONTACTO',
    
    // About
    'about.label': 'SOBRE NOSOTROS',
    'about.title': 'Le ayudamos a gestionar su negocio de forma segura y exitosa',
    'about.text1': 'Cyberlabforensics empresa 100% extremeña está especializada y se dedica exclusivamente a ofrecer servicios y soluciones de ciberseguridad. Nuestro objetivo es proteger eficazmente los activos digitales de nuestros clientes.',
    'about.text2': 'Con sede en Cáceres, Cyberlabforensics está específicamente diseñado para adaptarse a las necesidades particulares de ciberseguridad de cada cliente, garantizando la calidad y el éxito de cada proyecto.',
    'about.ourServices': 'NUESTROS SERVICIOS',
    
    // Services
    'services.label': 'NUESTROS SERVICIOS',
    'services.title': 'Servicios personalizados para su negocio',
    'services.threatIdentification': 'Identificación de Amenazas',
    'services.threatDesc': 'Detección proactiva de amenazas y vulnerabilidades en tu infraestructura.',
    'services.webProtection': 'Protección del Sitio Web',
    'services.webDesc': 'Protección integral contra ataques DDoS, malware y accesos no autorizados.',
    'services.ethicalHacking': 'Hacking Ético',
    'services.ethicalDesc': 'Pruebas de penetración para identificar vulnerabilidades antes que los atacantes.',
    'services.monitoring': 'Monitorización 24/7',
    'services.monitoringDesc': 'Vigilancia continua de tu infraestructura con respuesta inmediata a incidentes.',
    'services.dataProtection': 'Protección de Datos',
    'services.dataDesc': 'Cifrado y protección de datos sensibles cumpliendo con RGPD.',
    'services.cloudSecurity': 'Seguridad en la Nube',
    'services.cloudDesc': 'Protección de tus activos en entornos cloud públicos y privados.',
    
    // Forensics
    'forensics.label': 'INFORMÁTICA FORENSE',
    'forensics.title': 'Servicios de Informática Forense',
    'forensics.subtitle': 'Contamos con un equipo altamente especializado en peritajes informáticos judiciales. Nuestros expertos forenses digitales proporcionan análisis técnicos rigurosos con plena validez legal para procedimientos judiciales.',
    'forensics.digitalAnalysis': 'Análisis Forense Digital',
    'forensics.digitalDesc': 'Investigación exhaustiva de dispositivos digitales para recuperación y análisis de evidencias.',
    'forensics.dataRecovery': 'Recuperación de Datos',
    'forensics.dataRecoveryDesc': 'Extracción y recuperación de información crítica de dispositivos dañados o comprometidos.',
    'forensics.expertReports': 'Peritajes Informáticos Judiciales',
    'forensics.expertDesc': 'Elaboración de informes periciales con validez legal para procedimientos judiciales.',
    'forensics.deviceAnalysis': 'Análisis de Dispositivos',
    'forensics.deviceDesc': 'Examen forense de ordenadores, móviles, tablets y otros dispositivos electrónicos.',
    'forensics.chainCustody': 'Cadena de Custodia',
    'forensics.chainDesc': 'Preservación de evidencias digitales garantizando su integridad y validez legal.',
    'forensics.legalAdvice': 'Asesoramiento Legal',
    'forensics.legalDesc': 'Soporte experto en casos judiciales relacionados con delitos informáticos.',
    'forensics.teamTitle': 'Equipo Especializado en Peritajes Informáticos Judiciales',
    'forensics.teamText1': 'Nuestro equipo de peritos informáticos cuenta con amplia experiencia en la elaboración de informes periciales para procedimientos judiciales. Realizamos análisis forenses exhaustivos de dispositivos digitales, recuperación de evidencias y presentación de pruebas con total garantía legal.',
    'forensics.teamText2': 'Trabajamos en colaboración con abogados, juzgados y fuerzas de seguridad, garantizando la cadena de custodia y la integridad de las evidencias digitales en todo momento.',
    'forensics.legalValidity': 'Validez Legal',
    'forensics.certifiedExperts': 'Peritos Certificados',
    'forensics.technicalReports': 'Informes Técnicos',
    
    // Scanner
    'scanner.title': 'ESCÁNER DE VULNERABILIDADES',
    'scanner.subtitle': 'Analiza tu sitio web en tiempo real y descubre posibles vulnerabilidades de seguridad',
    'scanner.scan': 'ESCANEAR',
    'scanner.scanning': 'Escaneando...',
    'scanner.analyzing': 'Analizando puertos, certificados SSL, headers de seguridad y vulnerabilidades comunes...',
    'scanner.criticalCount': 'Críticas',
    'scanner.high': 'Altas',
    'scanner.medium': 'Medias',
    'scanner.low': 'Bajas',
    'scanner.securityScore': 'Puntuación de Seguridad',
    'scanner.excellent': 'Excelente - No se encontraron vulnerabilidades',
    'scanner.good': 'Bueno - Pocas vulnerabilidades detectadas',
    'scanner.regular': 'Regular - Se requiere atención',
    'scanner.criticalStatus': 'Crítico - Acción inmediata requerida',
    'scanner.detected': 'Vulnerabilidades Detectadas',
    'scanner.recommendation': 'Recomendación:',
    'scanner.needHelp': '¿Necesitas ayuda para solucionar estas vulnerabilidades?',
    'scanner.helpText': 'Nuestro equipo de expertos puede ayudarte a proteger tu sitio web',
    'scanner.contactNow': 'CONTACTAR AHORA',
    'scanner.inputPlaceholder': 'https://ejemplo.com',
    'scanner.severity.critical': 'CRITICA',
    'scanner.severity.high': 'ALTA',
    'scanner.severity.medium': 'MEDIA',
    'scanner.severity.low': 'BAJA',
    'scanner.mock.sqli.type': 'Inyeccion SQL',
    'scanner.mock.sqli.description': 'Se detecto una vulnerabilidad de inyeccion SQL en el formulario de login.',
    'scanner.mock.sqli.recommendation': 'Implementar prepared statements y validacion de entrada.',
    'scanner.mock.xss.type': 'XSS (Cross-Site Scripting)',
    'scanner.mock.xss.description': 'Posible vulnerabilidad XSS en campos de comentarios.',
    'scanner.mock.xss.recommendation': 'Sanitizar y escapar todo el contenido generado por usuarios.',
    'scanner.mock.ssl.type': 'SSL/TLS Debil',
    'scanner.mock.ssl.description': 'El certificado SSL utiliza protocolos obsoletos.',
    'scanner.mock.ssl.recommendation': 'Actualizar a TLS 1.3 y deshabilitar versiones antiguas.',
    'scanner.mock.headers.type': 'Headers de Seguridad',
    'scanner.mock.headers.description': 'Faltan headers de seguridad importantes (CSP, X-Frame-Options).',
    'scanner.mock.headers.recommendation': 'Configurar headers de seguridad HTTP apropiados.',
    'scanner.mock.version.type': 'Version de Software Expuesta',
    'scanner.mock.version.description': 'La version del servidor web esta expuesta en las respuestas HTTP.',
    'scanner.mock.version.recommendation': 'Ocultar informacion de version del servidor.',
    'scanner.mock.cookies.type': 'Cookies sin Secure Flag',
    'scanner.mock.cookies.description': 'Las cookies no tienen los flags Secure y HttpOnly.',
    'scanner.mock.cookies.recommendation': 'Configurar cookies con flags de seguridad apropiados.',
    
    // Compliance
    'compliance.label': 'CUMPLIMIENTO NORMATIVO',
    'compliance.title': 'Cumplimiento de Normativas y Estándares de Seguridad',
    'compliance.subtitle': 'Garantizamos el cumplimiento de las principales normativas y estándares de ciberseguridad y protección de datos a nivel nacional e internacional.',
    'compliance.auditTitle': 'Auditorías y Certificaciones de Cumplimiento',
    'compliance.auditText': 'Ofrecemos servicios de auditoría y consultoría para garantizar que tu organización cumple con todas las normativas aplicables. Nuestro equipo de expertos te guiará en el proceso de certificación y mantenimiento del cumplimiento normativo.',
    'compliance.requestAudit': 'SOLICITAR AUDITORÍA',
    'compliance.rgpd.subtitle': 'Reglamento General de Protección de Datos',
    'compliance.rgpd.description': 'Cumplimiento total con el RGPD (UE) 2016/679 para la protección de datos personales y privacidad en la Unión Europea.',
    'compliance.lopdgdd.subtitle': 'Ley Orgánica de Protección de Datos',
    'compliance.lopdgdd.description': 'Adaptación a la Ley Orgánica 3/2018 de Protección de Datos Personales y garantía de los derechos digitales en España.',
    'compliance.ens.subtitle': 'Esquema Nacional de Seguridad',
    'compliance.ens.description': 'Cumplimiento del Real Decreto 3/2010 del Esquema Nacional de Seguridad para sistemas de información del sector público.',
    'compliance.iso27001.subtitle': 'Gestión de Seguridad de la Información',
    'compliance.iso27001.description': 'Implementación de sistemas de gestión de seguridad de la información según estándares internacionales ISO/IEC 27001.',
    'compliance.nis2.subtitle': 'Directiva de Seguridad de Redes',
    'compliance.nis2.description': 'Preparación para la Directiva NIS2 (UE) 2022/2555 sobre medidas de ciberseguridad en redes y sistemas de información.',
    'compliance.lssi.subtitle': 'Ley de Servicios de la Sociedad de la Información',
    'compliance.lssi.description': 'Cumplimiento de la Ley 34/2002 de Servicios de la Sociedad de la Información y Comercio Electrónico.',
    
    // Why Choose Us
    'why.label': 'POR QUÉ ELEGIRNOS',
    'why.title': 'Somos su socio de confianza en el sector de ciberseguridad y TI',
    'why.subtitle': 'Cyberlabforensics ofrece servicios de misión crítica para detectar, responder y gestionar ciberataques, monitorizando 24/7 los desafíos de seguridad.',
    'why.blueTeam': 'Equipo de Blue Team',
    'why.blueDesc': 'Defensa proactiva y monitorización continua de tu infraestructura.',
    'why.redTeam': 'Equipo Red Team',
    'why.redDesc': 'Simulación de ataques reales para fortalecer tus defensas.',
    'why.incidentResponse': 'Respuesta a Incidentes',
    'why.incidentDesc': 'Equipo especializado disponible 24/7 para gestionar cualquier incidente.',
    'why.training': 'Formación y Concienciación',
    'why.trainingDesc': 'Capacitación continua para tu equipo en mejores prácticas de seguridad.',
    
    // SOC
    'soc.title': 'SOC - Centro de Operaciones de Seguridad de la Información',
    'soc.cybersecurity': 'Ciberseguridad',
    'soc.riskAssessment': 'Evaluación de Riesgos',
    'soc.networkSecurity': 'Seguridad de Red',
    'soc.serverMonitoring': 'Monitorización de Servidores',
    'soc.emailProtection': 'Protección de Correo Electrónico',
    'soc.backup': 'Copia de Seguridad y Recuperación',
    
    // CTA
    'cta.title': '¿Listo para la mejor experiencia en ciberseguridad?',
    'cta.subtitle': '¡Estamos seguros de que quedará 100% satisfecho con nuestros servicios!',
    'cta.contact': 'CONTACTO',
    
    // Footer
    'footer.description': 'Soluciones profesionales de ciberseguridad para proteger tu negocio.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.legal': 'Legal',
    'footer.legalNotice': 'Aviso Legal',
    'footer.privacy': 'Política de Privacidad',
    'footer.cookies': 'Política de Cookies',
    'footer.terms': 'Términos y Condiciones',
    'footer.contactInfo': 'Información de Contacto',
    'footer.address': 'EDIFICIO GARAJE 2.0 - C. Sta. Cristina, despacho S1, 10195 Cáceres',
    'footer.hours': 'Horario: 9:00 AM – 20:00 PM',
    'footer.rights': 'Todos los derechos reservados.',
  },
  en: {
    // Navbar
    'nav.home': 'HOME',
    'nav.about': 'ABOUT US',
    'nav.services': 'SERVICES',
    'nav.scanner': 'SCANNER',
    'nav.contact': 'CONTACT',
    'nav.freeConsultation': 'FREE CONSULTATION',
    
    // Hero
    'hero.title': 'CYBERSECURITY SOLUTIONS FOR YOUR BUSINESS',
    'hero.subtitle': 'Cyberlabforensics specializes in providing cybersecurity solutions. We effectively protect our clients\' digital assets.',
    'hero.knowUs': 'KNOW US',
    'hero.contact': 'CONTACT',
    
    // About
    'about.label': 'ABOUT US',
    'about.title': 'We help you manage your business safely and successfully',
    'about.text1': 'Cyberlabforensics, a 100% company from Extremadura, specializes exclusively in providing cybersecurity services and solutions. Our goal is to effectively protect our clients\' digital assets.',
    'about.text2': 'Based in Cáceres, Cyberlabforensics is specifically designed to adapt to each client\'s particular cybersecurity needs, ensuring quality and success in every project.',
    'about.ourServices': 'OUR SERVICES',
    
    // Services
    'services.label': 'OUR SERVICES',
    'services.title': 'Customized services for your business',
    'services.threatIdentification': 'Threat Identification',
    'services.threatDesc': 'Proactive detection of threats and vulnerabilities in your infrastructure.',
    'services.webProtection': 'Website Protection',
    'services.webDesc': 'Comprehensive protection against DDoS attacks, malware, and unauthorized access.',
    'services.ethicalHacking': 'Ethical Hacking',
    'services.ethicalDesc': 'Penetration testing to identify vulnerabilities before attackers do.',
    'services.monitoring': '24/7 Monitoring',
    'services.monitoringDesc': 'Continuous monitoring of your infrastructure with immediate incident response.',
    'services.dataProtection': 'Data Protection',
    'services.dataDesc': 'Encryption and protection of sensitive data complying with GDPR.',
    'services.cloudSecurity': 'Cloud Security',
    'services.cloudDesc': 'Protection of your assets in public and private cloud environments.',
    
    // Forensics
    'forensics.label': 'DIGITAL FORENSICS',
    'forensics.title': 'Digital Forensics Services',
    'forensics.subtitle': 'We have a highly specialized team in judicial computer expert reports. Our digital forensic experts provide rigorous technical analysis with full legal validity for judicial proceedings.',
    'forensics.digitalAnalysis': 'Digital Forensic Analysis',
    'forensics.digitalDesc': 'Comprehensive investigation of digital devices for evidence recovery and analysis.',
    'forensics.dataRecovery': 'Data Recovery',
    'forensics.dataRecoveryDesc': 'Extraction and recovery of critical information from damaged or compromised devices.',
    'forensics.expertReports': 'Judicial Computer Expert Reports',
    'forensics.expertDesc': 'Preparation of expert reports with legal validity for judicial proceedings.',
    'forensics.deviceAnalysis': 'Device Analysis',
    'forensics.deviceDesc': 'Forensic examination of computers, mobile phones, tablets, and other electronic devices.',
    'forensics.chainCustody': 'Chain of Custody',
    'forensics.chainDesc': 'Preservation of digital evidence ensuring its integrity and legal validity.',
    'forensics.legalAdvice': 'Legal Advice',
    'forensics.legalDesc': 'Expert support in judicial cases related to computer crimes.',
    'forensics.teamTitle': 'Specialized Team in Judicial Computer Expert Reports',
    'forensics.teamText1': 'Our team of computer experts has extensive experience in preparing expert reports for judicial proceedings. We perform comprehensive forensic analysis of digital devices, evidence recovery, and presentation of evidence with full legal guarantee.',
    'forensics.teamText2': 'We work in collaboration with lawyers, courts, and security forces, guaranteeing the chain of custody and integrity of digital evidence at all times.',
    'forensics.legalValidity': 'Legal Validity',
    'forensics.certifiedExperts': 'Certified Experts',
    'forensics.technicalReports': 'Technical Reports',
    
    // Scanner
    'scanner.title': 'VULNERABILITY SCANNER',
    'scanner.subtitle': 'Analyze your website in real-time and discover potential security vulnerabilities',
    'scanner.scan': 'SCAN',
    'scanner.scanning': 'Scanning...',
    'scanner.analyzing': 'Analyzing ports, SSL certificates, security headers, and common vulnerabilities...',
    'scanner.criticalCount': 'Critical',
    'scanner.high': 'High',
    'scanner.medium': 'Medium',
    'scanner.low': 'Low',
    'scanner.securityScore': 'Security Score',
    'scanner.excellent': 'Excellent - No vulnerabilities found',
    'scanner.good': 'Good - Few vulnerabilities detected',
    'scanner.regular': 'Fair - Attention required',
    'scanner.criticalStatus': 'Critical - Immediate action required',
    'scanner.detected': 'Detected Vulnerabilities',
    'scanner.recommendation': 'Recommendation:',
    'scanner.needHelp': 'Need help fixing these vulnerabilities?',
    'scanner.helpText': 'Our team of experts can help you protect your website',
    'scanner.contactNow': 'CONTACT NOW',
    'scanner.inputPlaceholder': 'https://example.com',
    'scanner.severity.critical': 'CRITICAL',
    'scanner.severity.high': 'HIGH',
    'scanner.severity.medium': 'MEDIUM',
    'scanner.severity.low': 'LOW',
    'scanner.mock.sqli.type': 'SQL Injection',
    'scanner.mock.sqli.description': 'An SQL injection vulnerability was detected in the login form.',
    'scanner.mock.sqli.recommendation': 'Implement prepared statements and input validation.',
    'scanner.mock.xss.type': 'XSS (Cross-Site Scripting)',
    'scanner.mock.xss.description': 'Possible XSS vulnerability in comment fields.',
    'scanner.mock.xss.recommendation': 'Sanitize and escape all user-generated content.',
    'scanner.mock.ssl.type': 'Weak SSL/TLS',
    'scanner.mock.ssl.description': 'The SSL certificate uses obsolete protocols.',
    'scanner.mock.ssl.recommendation': 'Upgrade to TLS 1.3 and disable older versions.',
    'scanner.mock.headers.type': 'Security Headers',
    'scanner.mock.headers.description': 'Important security headers are missing (CSP, X-Frame-Options).',
    'scanner.mock.headers.recommendation': 'Configure appropriate HTTP security headers.',
    'scanner.mock.version.type': 'Exposed Software Version',
    'scanner.mock.version.description': 'The web server version is exposed in HTTP responses.',
    'scanner.mock.version.recommendation': 'Hide server version information.',
    'scanner.mock.cookies.type': 'Cookies Without Secure Flag',
    'scanner.mock.cookies.description': 'Cookies do not include Secure and HttpOnly flags.',
    'scanner.mock.cookies.recommendation': 'Configure cookies with appropriate security flags.',
    
    // Compliance
    'compliance.label': 'REGULATORY COMPLIANCE',
    'compliance.title': 'Compliance with Regulations and Security Standards',
    'compliance.subtitle': 'We guarantee compliance with the main cybersecurity and data protection regulations and standards at national and international levels.',
    'compliance.auditTitle': 'Compliance Audits and Certifications',
    'compliance.auditText': 'We offer audit and consulting services to ensure your organization complies with all applicable regulations. Our team of experts will guide you through the certification and compliance maintenance process.',
    'compliance.requestAudit': 'REQUEST AUDIT',
    'compliance.rgpd.subtitle': 'General Data Protection Regulation',
    'compliance.rgpd.description': 'Full compliance with GDPR (EU) 2016/679 for personal data protection and privacy in the European Union.',
    'compliance.lopdgdd.subtitle': 'Organic Data Protection Law',
    'compliance.lopdgdd.description': 'Adaptation to Organic Law 3/2018 on Personal Data Protection and guarantee of digital rights in Spain.',
    'compliance.ens.subtitle': 'National Security Framework',
    'compliance.ens.description': 'Compliance with Royal Decree 3/2010 of the National Security Framework for public sector information systems.',
    'compliance.iso27001.subtitle': 'Information Security Management',
    'compliance.iso27001.description': 'Implementation of information security management systems according to international ISO/IEC 27001 standards.',
    'compliance.nis2.subtitle': 'Network Security Directive',
    'compliance.nis2.description': 'Preparation for NIS2 Directive (EU) 2022/2555 on cybersecurity measures in network and information systems.',
    'compliance.lssi.subtitle': 'Information Society Services Law',
    'compliance.lssi.description': 'Compliance with Law 34/2002 on Information Society Services and Electronic Commerce.',
    
    // Why Choose Us
    'why.label': 'WHY CHOOSE US',
    'why.title': 'We are your trusted partner in cybersecurity and IT',
    'why.subtitle': 'Cyberlabforensics offers mission-critical services to detect, respond to, and manage cyberattacks, monitoring security challenges 24/7.',
    'why.blueTeam': 'Blue Team',
    'why.blueDesc': 'Proactive defense and continuous monitoring of your infrastructure.',
    'why.redTeam': 'Red Team',
    'why.redDesc': 'Simulation of real attacks to strengthen your defenses.',
    'why.incidentResponse': 'Incident Response',
    'why.incidentDesc': 'Specialized team available 24/7 to manage any incident.',
    'why.training': 'Training and Awareness',
    'why.trainingDesc': 'Continuous training for your team in security best practices.',
    
    // SOC
    'soc.title': 'SOC - Security Operations Center',
    'soc.cybersecurity': 'Cybersecurity',
    'soc.riskAssessment': 'Risk Assessment',
    'soc.networkSecurity': 'Network Security',
    'soc.serverMonitoring': 'Server Monitoring',
    'soc.emailProtection': 'Email Protection',
    'soc.backup': 'Backup and Recovery',
    
    // CTA
    'cta.title': 'Ready for the best cybersecurity experience?',
    'cta.subtitle': 'We are confident you will be 100% satisfied with our services!',
    'cta.contact': 'CONTACT',
    
    // Footer
    'footer.description': 'Professional cybersecurity solutions to protect your business.',
    'footer.quickLinks': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.legalNotice': 'Legal Notice',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.terms': 'Terms and Conditions',
    'footer.contactInfo': 'Contact Information',
    'footer.address': 'GARAJE 2.0 BUILDING - C. Sta. Cristina, office S1, 10195 Cáceres',
    'footer.hours': 'Hours: 9:00 AM – 8:00 PM',
    'footer.rights': 'All rights reserved.',
  },
  fr: {
    // Navbar
    'nav.home': 'ACCUEIL',
    'nav.about': 'QUI SOMMES-NOUS',
    'nav.services': 'SERVICES',
    'nav.scanner': 'SCANNER',
    'nav.contact': 'CONTACT',
    'nav.freeConsultation': 'CONSULTATION GRATUITE',
    
    // Hero
    'hero.title': 'SOLUTIONS DE CYBERSÉCURITÉ POUR VOTRE ENTREPRISE',
    'hero.subtitle': 'Cyberlabforensics est spécialisé dans la fourniture de solutions de cybersécurité. Nous protégeons efficacement les actifs numériques de nos clients.',
    'hero.knowUs': 'DÉCOUVREZ-NOUS',
    'hero.contact': 'CONTACT',
    
    // About
    'about.label': 'QUI SOMMES-NOUS',
    'about.title': 'Nous vous aidons à gérer votre entreprise en toute sécurité et avec succès',
    'about.text1': 'Cyberlabforensics, entreprise 100% d\'Estrémadure, est spécialisée exclusivement dans la fourniture de services et solutions de cybersécurité. Notre objectif est de protéger efficacement les actifs numériques de nos clients.',
    'about.text2': 'Basé à Cáceres, Cyberlabforensics est spécifiquement conçu pour s\'adapter aux besoins particuliers de cybersécurité de chaque client, garantissant la qualité et le succès de chaque projet.',
    'about.ourServices': 'NOS SERVICES',
    
    // Services
    'services.label': 'NOS SERVICES',
    'services.title': 'Services personnalisés pour votre entreprise',
    'services.threatIdentification': 'Identification des Menaces',
    'services.threatDesc': 'Détection proactive des menaces et vulnérabilités dans votre infrastructure.',
    'services.webProtection': 'Protection du Site Web',
    'services.webDesc': 'Protection complète contre les attaques DDoS, les malwares et les accès non autorisés.',
    'services.ethicalHacking': 'Hacking Éthique',
    'services.ethicalDesc': 'Tests de pénétration pour identifier les vulnérabilités avant les attaquants.',
    'services.monitoring': 'Surveillance 24/7',
    'services.monitoringDesc': 'Surveillance continue de votre infrastructure avec réponse immédiate aux incidents.',
    'services.dataProtection': 'Protection des Données',
    'services.dataDesc': 'Chiffrement et protection des données sensibles conformément au RGPD.',
    'services.cloudSecurity': 'Sécurité Cloud',
    'services.cloudDesc': 'Protection de vos actifs dans des environnements cloud publics et privés.',
    
    // Forensics
    'forensics.label': 'INFORMATIQUE LÉGALE',
    'forensics.title': 'Services d\'Informatique Légale',
    'forensics.subtitle': 'Nous disposons d\'une équipe hautement spécialisée en expertises informatiques judiciaires. Nos experts en criminalistique numérique fournissent des analyses techniques rigoureuses avec pleine validité légale pour les procédures judiciaires.',
    'forensics.digitalAnalysis': 'Analyse Criminalistique Numérique',
    'forensics.digitalDesc': 'Investigation exhaustive des appareils numériques pour la récupération et l\'analyse de preuves.',
    'forensics.dataRecovery': 'Récupération de Données',
    'forensics.dataRecoveryDesc': 'Extraction et récupération d\'informations critiques d\'appareils endommagés ou compromis.',
    'forensics.expertReports': 'Expertises Informatiques Judiciaires',
    'forensics.expertDesc': 'Élaboration de rapports d\'expertise avec validité légale pour les procédures judiciaires.',
    'forensics.deviceAnalysis': 'Analyse d\'Appareils',
    'forensics.deviceDesc': 'Examen criminalistique d\'ordinateurs, téléphones mobiles, tablettes et autres appareils électroniques.',
    'forensics.chainCustody': 'Chaîne de Traçabilité',
    'forensics.chainDesc': 'Préservation des preuves numériques garantissant leur intégrité et validité légale.',
    'forensics.legalAdvice': 'Conseil Juridique',
    'forensics.legalDesc': 'Support expert dans les affaires judiciaires liées aux délits informatiques.',
    'forensics.teamTitle': 'Équipe Spécialisée en Expertises Informatiques Judiciaires',
    'forensics.teamText1': 'Notre équipe d\'experts informatiques possède une vaste expérience dans l\'élaboration de rapports d\'expertise pour les procédures judiciaires. Nous effectuons des analyses criminalistiques exhaustives d\'appareils numériques, la récupération de preuves et la présentation de preuves avec garantie légale totale.',
    'forensics.teamText2': 'Nous travaillons en collaboration avec des avocats, des tribunaux et des forces de sécurité, garantissant la chaîne de traçabilité et l\'intégrité des preuves numériques à tout moment.',
    'forensics.legalValidity': 'Validité Légale',
    'forensics.certifiedExperts': 'Experts Certifiés',
    'forensics.technicalReports': 'Rapports Techniques',
    
    // Scanner
    'scanner.title': 'SCANNER DE VULNÉRABILITÉS',
    'scanner.subtitle': 'Analysez votre site web en temps réel et découvrez les vulnérabilités de sécurité potentielles',
    'scanner.scan': 'SCANNER',
    'scanner.scanning': 'Analyse en cours...',
    'scanner.analyzing': 'Analyse des ports, certificats SSL, en-têtes de sécurité et vulnérabilités courantes...',
    'scanner.criticalCount': 'Critiques',
    'scanner.high': 'Élevées',
    'scanner.medium': 'Moyennes',
    'scanner.low': 'Faibles',
    'scanner.securityScore': 'Score de Sécurité',
    'scanner.excellent': 'Excellent - Aucune vulnérabilité trouvée',
    'scanner.good': 'Bon - Peu de vulnérabilités détectées',
    'scanner.regular': 'Moyen - Attention requise',
    'scanner.criticalStatus': 'Critique - Action immédiate requise',
    'scanner.detected': 'Vulnérabilités Détectées',
    'scanner.recommendation': 'Recommandation:',
    'scanner.needHelp': 'Besoin d\'aide pour corriger ces vulnérabilités?',
    'scanner.helpText': 'Notre équipe d\'experts peut vous aider à protéger votre site web',
    'scanner.contactNow': 'CONTACTEZ-NOUS',
    'scanner.inputPlaceholder': 'https://exemple.com',
    'scanner.severity.critical': 'CRITIQUE',
    'scanner.severity.high': 'ELEVEE',
    'scanner.severity.medium': 'MOYENNE',
    'scanner.severity.low': 'FAIBLE',
    'scanner.mock.sqli.type': 'Injection SQL',
    'scanner.mock.sqli.description': 'Une vulnerabilite d\'injection SQL a ete detectee dans le formulaire de connexion.',
    'scanner.mock.sqli.recommendation': 'Implementer des requetes preparees et une validation des entrees.',
    'scanner.mock.xss.type': 'XSS (Cross-Site Scripting)',
    'scanner.mock.xss.description': 'Vulnerabilite XSS possible dans les champs de commentaires.',
    'scanner.mock.xss.recommendation': 'Assainir et echapper tout contenu genere par les utilisateurs.',
    'scanner.mock.ssl.type': 'SSL/TLS Faible',
    'scanner.mock.ssl.description': 'Le certificat SSL utilise des protocoles obsoletes.',
    'scanner.mock.ssl.recommendation': 'Passer a TLS 1.3 et desactiver les anciennes versions.',
    'scanner.mock.headers.type': 'En-Tetes de Securite',
    'scanner.mock.headers.description': 'Des en-tetes de securite importants manquent (CSP, X-Frame-Options).',
    'scanner.mock.headers.recommendation': 'Configurer des en-tetes HTTP de securite appropries.',
    'scanner.mock.version.type': 'Version Logicielle Exposee',
    'scanner.mock.version.description': 'La version du serveur web est exposee dans les reponses HTTP.',
    'scanner.mock.version.recommendation': 'Masquer les informations de version du serveur.',
    'scanner.mock.cookies.type': 'Cookies Sans Secure Flag',
    'scanner.mock.cookies.description': 'Les cookies n\'incluent pas les attributs Secure et HttpOnly.',
    'scanner.mock.cookies.recommendation': 'Configurer les cookies avec des attributs de securite appropries.',
    
    // Compliance
    'compliance.label': 'CONFORMITÉ RÉGLEMENTAIRE',
    'compliance.title': 'Conformité aux Réglementations et Normes de Sécurité',
    'compliance.subtitle': 'Nous garantissons la conformité aux principales réglementations et normes de cybersécurité et de protection des données aux niveaux national et international.',
    'compliance.auditTitle': 'Audits et Certifications de Conformité',
    'compliance.auditText': 'Nous offrons des services d\'audit et de conseil pour garantir que votre organisation respecte toutes les réglementations applicables. Notre équipe d\'experts vous guidera dans le processus de certification et de maintien de la conformité.',
    'compliance.requestAudit': 'DEMANDER UN AUDIT',
    'compliance.rgpd.subtitle': 'Reglement General sur la Protection des Donnees',
    'compliance.rgpd.description': 'Conformite totale au RGPD (UE) 2016/679 pour la protection des donnees personnelles et de la vie privee dans l\'Union europeenne.',
    'compliance.lopdgdd.subtitle': 'Loi Organique sur la Protection des Donnees',
    'compliance.lopdgdd.description': 'Adaptation a la Loi Organique 3/2018 sur la protection des donnees personnelles et la garantie des droits numeriques en Espagne.',
    'compliance.ens.subtitle': 'Schema National de Securite',
    'compliance.ens.description': 'Conformite au Decret Royal 3/2010 du Schema National de Securite pour les systemes d\'information du secteur public.',
    'compliance.iso27001.subtitle': 'Gestion de la Securite de l\'Information',
    'compliance.iso27001.description': 'Mise en oeuvre de systemes de gestion de la securite de l\'information selon les normes internationales ISO/IEC 27001.',
    'compliance.nis2.subtitle': 'Directive de Securite des Reseaux',
    'compliance.nis2.description': 'Preparation a la Directive NIS2 (UE) 2022/2555 sur les mesures de cybersécurité pour les reseaux et systemes d\'information.',
    'compliance.lssi.subtitle': 'Loi sur les Services de la Societe de l\'Information',
    'compliance.lssi.description': 'Conformite a la Loi 34/2002 sur les services de la societe de l\'information et le commerce electronique.',
    
    // Why Choose Us
    'why.label': 'POURQUOI NOUS CHOISIR',
    'why.title': 'Nous sommes votre partenaire de confiance en cybersécurité et IT',
    'why.subtitle': 'Cyberlabforensics offre des services critiques pour détecter, répondre et gérer les cyberattaques, surveillant les défis de sécurité 24/7.',
    'why.blueTeam': 'Équipe Blue Team',
    'why.blueDesc': 'Défense proactive et surveillance continue de votre infrastructure.',
    'why.redTeam': 'Équipe Red Team',
    'why.redDesc': 'Simulation d\'attaques réelles pour renforcer vos défenses.',
    'why.incidentResponse': 'Réponse aux Incidents',
    'why.incidentDesc': 'Équipe spécialisée disponible 24/7 pour gérer tout incident.',
    'why.training': 'Formation et Sensibilisation',
    'why.trainingDesc': 'Formation continue pour votre équipe aux meilleures pratiques de sécurité.',
    
    // SOC
    'soc.title': 'SOC - Centre d\'Opérations de Sécurité',
    'soc.cybersecurity': 'Cybersécurité',
    'soc.riskAssessment': 'Évaluation des Risques',
    'soc.networkSecurity': 'Sécurité Réseau',
    'soc.serverMonitoring': 'Surveillance des Serveurs',
    'soc.emailProtection': 'Protection Email',
    'soc.backup': 'Sauvegarde et Récupération',
    
    // CTA
    'cta.title': 'Prêt pour la meilleure expérience en cybersécurité?',
    'cta.subtitle': 'Nous sommes convaincus que vous serez 100% satisfait de nos services!',
    'cta.contact': 'CONTACT',
    
    // Footer
    'footer.description': 'Solutions professionnelles de cybersécurité pour protéger votre entreprise.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.legal': 'Légal',
    'footer.legalNotice': 'Mentions Légales',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.cookies': 'Politique de Cookies',
    'footer.terms': 'Termes et Conditions',
    'footer.contactInfo': 'Informations de Contact',
    'footer.address': 'BÂTIMENT GARAJE 2.0 - C. Sta. Cristina, bureau S1, 10195 Cáceres',
    'footer.hours': 'Horaires: 9h00 – 20h00',
    'footer.rights': 'Tous droits réservés.',
  },

  it: {
    // Navbar
    'nav.home': 'HOME',
    'nav.about': 'CHI SIAMO',
    'nav.services': 'SERVICES',
    'nav.scanner': 'SCANNER',
    'nav.contact': 'CONTACT',
    'nav.freeConsultation': 'CONSULENZA GRATUITA',
    
    // Hero
    'hero.title': 'SOLUZIONI DI CYBERSECURITY PER LA TUA AZIENDA',
    'hero.subtitle': 'Cyberlabforensics e specializzata nell\'offerta di soluzioni di cybersecurity. Proteggiamo in modo efficace gli asset digitali dei nostri clienti.',
    'hero.knowUs': 'SCOPRICI',
    'hero.contact': 'CONTATTO',
    
    // About
    'about.label': 'CHI SIAMO',
    'about.title': 'Ti aiutiamo a gestire la tua azienda in modo sicuro e con successo',
    'about.text1': 'Cyberlabforensics, azienda 100% dell\'Estremadura, e specializzata esclusivamente nell\'offerta di servizi e soluzioni di cybersecurity. Il nostro obiettivo e proteggere efficacemente gli asset digitali dei nostri clienti.',
    'about.text2': 'Con sede a Caceres, Cyberlabforensics e progettata specificamente per adattarsi alle esigenze particolari di cybersecurity di ogni cliente, garantendo qualita e successo in ogni progetto.',
    'about.ourServices': 'I NOSTRI SERVIZI',
    
    // Services
    'services.label': 'I NOSTRI SERVIZI',
    'services.title': 'Servizi personalizzati per la tua azienda',
    'services.threatIdentification': 'Identificazione delle Minacce',
    'services.threatDesc': 'Rilevamento proattivo di minacce e vulnerabilita nella tua infrastruttura.',
    'services.webProtection': 'Protezione del Sito Web',
    'services.webDesc': 'Protezione completa contro attacchi DDoS, malware e accessi non autorizzati.',
    'services.ethicalHacking': 'Hacking Etico',
    'services.ethicalDesc': 'Test di penetrazione per identificare le vulnerabilita prima degli attaccanti.',
    'services.monitoring': 'Monitoraggio 24/7',
    'services.monitoringDesc': 'Monitoraggio continuo della tua infrastruttura con risposta immediata agli incidenti.',
    'services.dataProtection': 'Protezione dei Dati',
    'services.dataDesc': 'Cifratura e protezione dei dati sensibili in conformita al GDPR.',
    'services.cloudSecurity': 'Sicurezza Cloud',
    'services.cloudDesc': 'Protezione dei tuoi asset in ambienti cloud pubblici e privati.',
    
    // Forensics
    'forensics.label': 'INFORMATICA FORENSE',
    'forensics.title': 'Servizi di Informatica Forense',
    'forensics.subtitle': 'Disponiamo di un team altamente specializzato in perizie informatiche giudiziarie. I nostri esperti di forensica digitale forniscono analisi tecniche rigorose con piena validita legale per i procedimenti giudiziari.',
    'forensics.digitalAnalysis': 'Analisi Forense Digitale',
    'forensics.digitalDesc': 'Indagine esaustiva dei dispositivi digitali per il recupero e l\'analisi delle prove.',
    'forensics.dataRecovery': 'Recupero Dati',
    'forensics.dataRecoveryDesc': 'Estrazione e recupero di informazioni critiche da dispositivi danneggiati o compromessi.',
    'forensics.expertReports': 'Perizie Informatiche Giudiziarie',
    'forensics.expertDesc': 'Redazione di relazioni peritali con validita legale per i procedimenti giudiziari.',
    'forensics.deviceAnalysis': 'Analisi dei Dispositivi',
    'forensics.deviceDesc': 'Esame forense di computer, telefoni cellulari, tablet e altri dispositivi elettronici.',
    'forensics.chainCustody': 'Catena di Custodia',
    'forensics.chainDesc': 'Conservazione delle prove digitali garantendone integrita e validita legale.',
    'forensics.legalAdvice': 'Consulenza Legale',
    'forensics.legalDesc': 'Supporto esperto in casi giudiziari legati ai reati informatici.',
    'forensics.teamTitle': 'Team Specializzato in Perizie Informatiche Giudiziarie',
    'forensics.teamText1': 'Il nostro team di periti informatici ha ampia esperienza nella redazione di relazioni peritali per procedimenti giudiziari. Eseguiamo analisi forensi complete di dispositivi digitali, recupero di prove e presentazione delle evidenze con totale garanzia legale.',
    'forensics.teamText2': 'Collaboriamo con avvocati, tribunali e forze di sicurezza, garantendo in ogni momento la catena di custodia e l\'integrita delle prove digitali.',
    'forensics.legalValidity': 'Validita Legale',
    'forensics.certifiedExperts': 'Periti Certificati',
    'forensics.technicalReports': 'Rapporti Tecnici',
    
    // Scanner
    'scanner.title': 'SCANNER DI VULNERABILITA',
    'scanner.subtitle': 'Analizza il tuo sito web in tempo reale e scopri possibili vulnerabilita di sicurezza',
    'scanner.scan': 'SCANNER',
    'scanner.scanning': 'Scansione in corso...',
    'scanner.analyzing': 'Analisi di porte, certificati SSL, header di sicurezza e vulnerabilita comuni...',
    'scanner.criticalCount': 'Critiche',
    'scanner.high': 'Alte',
    'scanner.medium': 'Medie',
    'scanner.low': 'Basse',
    'scanner.securityScore': 'Punteggio di Sicurezza',
    'scanner.excellent': 'Eccellente - Nessuna vulnerabilita trovata',
    'scanner.good': 'Buono - Poche vulnerabilita rilevate',
    'scanner.regular': 'Discreto - Richiede attenzione',
    'scanner.criticalStatus': 'Critico - Azione immediata richiesta',
    'scanner.detected': 'Vulnerabilita Rilevate',
    'scanner.recommendation': 'Raccomandazione:',
    'scanner.needHelp': 'Hai bisogno di aiuto per correggere queste vulnerabilita?',
    'scanner.helpText': 'Il nostro team di esperti puo aiutarti a proteggere il tuo sito web',
    'scanner.contactNow': 'CONTATTACI ORA',
    'scanner.inputPlaceholder': 'https://esempio.com',
    'scanner.severity.critical': 'CRITICA',
    'scanner.severity.high': 'ALTA',
    'scanner.severity.medium': 'MEDIA',
    'scanner.severity.low': 'BASSA',
    'scanner.mock.sqli.type': 'Iniezione SQL',
    'scanner.mock.sqli.description': 'E stata rilevata una vulnerabilita di iniezione SQL nel modulo di login.',
    'scanner.mock.sqli.recommendation': 'Implementare prepared statement e validazione degli input.',
    'scanner.mock.xss.type': 'XSS (Cross-Site Scripting)',
    'scanner.mock.xss.description': 'Possibile vulnerabilita XSS nei campi commento.',
    'scanner.mock.xss.recommendation': 'Sanificare ed effettuare escape di tutti i contenuti generati dagli utenti.',
    'scanner.mock.ssl.type': 'SSL/TLS Debole',
    'scanner.mock.ssl.description': 'Il certificato SSL utilizza protocolli obsoleti.',
    'scanner.mock.ssl.recommendation': 'Aggiornare a TLS 1.3 e disabilitare le versioni precedenti.',
    'scanner.mock.headers.type': 'Header di Sicurezza',
    'scanner.mock.headers.description': 'Mancano header di sicurezza importanti (CSP, X-Frame-Options).',
    'scanner.mock.headers.recommendation': 'Configurare header HTTP di sicurezza appropriati.',
    'scanner.mock.version.type': 'Versione Software Esposta',
    'scanner.mock.version.description': 'La versione del server web e esposta nelle risposte HTTP.',
    'scanner.mock.version.recommendation': 'Nascondere le informazioni di versione del server.',
    'scanner.mock.cookies.type': 'Cookie Senza Secure Flag',
    'scanner.mock.cookies.description': 'I cookie non hanno i flag Secure e HttpOnly.',
    'scanner.mock.cookies.recommendation': 'Configurare i cookie con flag di sicurezza appropriati.',
    
    // Compliance
    'compliance.label': 'CONFORMITA NORMATIVA',
    'compliance.title': 'Conformita a Normative e Standard di Sicurezza',
    'compliance.subtitle': 'Garantiamo la conformita alle principali normative e standard di cybersecurity e protezione dei dati a livello nazionale e internazionale.',
    'compliance.auditTitle': 'Audit e Certificazioni di Conformita',
    'compliance.auditText': 'Offriamo servizi di audit e consulenza per garantire che la tua organizzazione rispetti tutte le normative applicabili. Il nostro team di esperti ti guidera nel processo di certificazione e mantenimento della conformita.',
    'compliance.requestAudit': 'RICHIEDI AUDIT',
    'compliance.rgpd.subtitle': 'Regolamento Generale sulla Protezione dei Dati',
    'compliance.rgpd.description': 'Piena conformita al RGPD (UE) 2016/679 per la protezione dei dati personali e della privacy nell\'Unione Europea.',
    'compliance.lopdgdd.subtitle': 'Legge Organica sulla Protezione dei Dati',
    'compliance.lopdgdd.description': 'Adeguamento alla Legge Organica 3/2018 sulla protezione dei dati personali e garanzia dei diritti digitali in Spagna.',
    'compliance.ens.subtitle': 'Schema Nazionale di Sicurezza',
    'compliance.ens.description': 'Conformita al Regio Decreto 3/2010 dello Schema Nazionale di Sicurezza per i sistemi informativi del settore pubblico.',
    'compliance.iso27001.subtitle': 'Gestione della Sicurezza delle Informazioni',
    'compliance.iso27001.description': 'Implementazione di sistemi di gestione della sicurezza delle informazioni secondo gli standard internazionali ISO/IEC 27001.',
    'compliance.nis2.subtitle': 'Direttiva sulla Sicurezza delle Reti',
    'compliance.nis2.description': 'Preparazione alla Direttiva NIS2 (UE) 2022/2555 sulle misure di cybersecurity nelle reti e nei sistemi informativi.',
    'compliance.lssi.subtitle': 'Legge sui Servizi della Societa dell\'Informazione',
    'compliance.lssi.description': 'Conformita alla Legge 34/2002 sui Servizi della Societa dell\'Informazione e sul Commercio Elettronico.',
    
    // Why Choose Us
    'why.label': 'PERCHE SCEGLIERCI',
    'why.title': 'Siamo il tuo partner di fiducia in cybersecurity e IT',
    'why.subtitle': 'Cyberlabforensics offre servizi mission-critical per rilevare, rispondere e gestire i cyberattacchi, monitorando le sfide di sicurezza 24/7.',
    'why.blueTeam': 'Équipe Blue Team',
    'why.blueDesc': 'Difesa proattiva e monitoraggio continuo della tua infrastruttura.',
    'why.redTeam': 'Équipe Red Team',
    'why.redDesc': 'Simulazione di attacchi reali per rafforzare le tue difese.',
    'why.incidentResponse': 'Risposta agli Incidenti',
    'why.incidentDesc': 'Team specializzato disponibile 24/7 per gestire qualsiasi incidente.',
    'why.training': 'Formazione e Consapevolezza',
    'why.trainingDesc': 'Formazione continua per il tuo team sulle migliori pratiche di sicurezza.',
    
    // SOC
    'soc.title': 'SOC - Centro Operativo di Sicurezza',
    'soc.cybersecurity': 'Cybersecurity',
    'soc.riskAssessment': 'Valutazione dei Rischi',
    'soc.networkSecurity': 'Sicurezza di Rete',
    'soc.serverMonitoring': 'Monitoraggio dei Server',
    'soc.emailProtection': 'Protezione Email',
    'soc.backup': 'Backup e Ripristino',
    
    // CTA
    'cta.title': 'Pronto per la migliore esperienza in cybersecurity?',
    'cta.subtitle': 'Siamo certi che sarai soddisfatto al 100% dei nostri servizi!',
    'cta.contact': 'CONTATTO',
    
    // Footer
    'footer.description': 'Soluzioni professionali di cybersecurity per proteggere la tua azienda.',
    'footer.quickLinks': 'Link Rapidi',
    'footer.legal': 'Legale',
    'footer.legalNotice': 'Avviso Legale',
    'footer.privacy': 'Informativa sulla Privacy',
    'footer.cookies': 'Politica dei Cookie',
    'footer.terms': 'Termini e Condizioni',
    'footer.contactInfo': 'Informazioni di Contatto',
    'footer.address': 'EDIFICIO GARAJE 2.0 - C. Sta. Cristina, ufficio S1, 10195 Caceres',
    'footer.hours': 'Orario: 9:00 - 20:00',
    'footer.rights': 'Tutti i diritti riservati.',
  },

  de: {
        // Navbar
    'nav.home': 'STARTSEITE',
    'nav.about': 'UBER UNS',
    'nav.services': 'SERVICES',
    'nav.scanner': 'SCANNER',
    'nav.contact': 'CONTACT',
    'nav.freeConsultation': 'KOSTENLOSE BERATUNG',
    
    // Hero
    'hero.title': 'CYBERSICHERHEITSLOSUNGEN FUR IHR UNTERNEHMEN',
    'hero.subtitle': 'Cyberlabforensics ist auf die Bereitstellung von Cybersicherheitslosungen spezialisiert. Wir schutzen die digitalen Vermogenswerte unserer Kunden effektiv.',
    'hero.knowUs': 'LERNEN SIE UNS KENNEN',
    'hero.contact': 'KONTAKT',
    
    // About
    'about.label': 'UBER UNS',
    'about.title': 'Wir helfen Ihnen, Ihr Unternehmen sicher und erfolgreich zu fuhren',
    'about.text1': 'Cyberlabforensics, ein zu 100% in Extremadura ansassiges Unternehmen, ist ausschliesslich auf Cybersicherheitsdienste und -losungen spezialisiert. Unser Ziel ist es, die digitalen Vermogenswerte unserer Kunden effektiv zu schutzen.',
    'about.text2': 'Mit Sitz in Caceres ist Cyberlabforensics speziell darauf ausgerichtet, sich an die individuellen Cybersicherheitsbedurfnisse jedes Kunden anzupassen und dabei Qualitat und Erfolg in jedem Projekt zu gewahrleisten.',
    'about.ourServices': 'UNSERE DIENSTLEISTUNGEN',
    
    // Services
    'services.label': 'UNSERE DIENSTLEISTUNGEN',
    'services.title': 'Massgeschneiderte Dienstleistungen fur Ihr Unternehmen',
    'services.threatIdentification': 'Bedrohungserkennung',
    'services.threatDesc': 'Proaktive Erkennung von Bedrohungen und Schwachstellen in Ihrer Infrastruktur.',
    'services.webProtection': 'Webseitenschutz',
    'services.webDesc': 'Umfassender Schutz vor DDoS-Angriffen, Malware und unbefugtem Zugriff.',
    'services.ethicalHacking': 'Ethisches Hacking',
    'services.ethicalDesc': 'Penetrationstests zur Identifizierung von Schwachstellen, bevor Angreifer sie ausnutzen.',
    'services.monitoring': '24/7-Uberwachung',
    'services.monitoringDesc': 'Kontinuierliche Uberwachung Ihrer Infrastruktur mit sofortiger Reaktion auf Vorfalle.',
    'services.dataProtection': 'Datenschutz',
    'services.dataDesc': 'Verschlusselung und Schutz sensibler Daten gemass DSGVO.',
    'services.cloudSecurity': 'Cloud-Sicherheit',
    'services.cloudDesc': 'Schutz Ihrer Assets in offentlichen und privaten Cloud-Umgebungen.',
    
    // Forensics
    'forensics.label': 'DIGITALE FORENSIK',
    'forensics.title': 'Dienstleistungen der Digitalen Forensik',
    'forensics.subtitle': 'Wir verfugen uber ein hochspezialisiertes Team fur gerichtliche IT-Gutachten. Unsere Experten fur digitale Forensik liefern strenge technische Analysen mit voller rechtlicher Gultigkeit fur Gerichtsverfahren.',
    'forensics.digitalAnalysis': 'Digitale Forensische Analyse',
    'forensics.digitalDesc': 'Umfassende Untersuchung digitaler Gerate zur Wiederherstellung und Analyse von Beweismitteln.',
    'forensics.dataRecovery': 'Datenwiederherstellung',
    'forensics.dataRecoveryDesc': 'Extraktion und Wiederherstellung kritischer Informationen von beschadigten oder kompromittierten Geraten.',
    'forensics.expertReports': 'Gerichtliche IT-Gutachten',
    'forensics.expertDesc': 'Erstellung von Gutachten mit rechtlicher Gultigkeit fur Gerichtsverfahren.',
    'forensics.deviceAnalysis': 'Gerateanalyse',
    'forensics.deviceDesc': 'Forensische Untersuchung von Computern, Mobiltelefonen, Tablets und anderen elektronischen Geraten.',
    'forensics.chainCustody': 'Beweismittelkette',
    'forensics.chainDesc': 'Sicherung digitaler Beweise unter Gewahrleistung von Integritat und rechtlicher Gultigkeit.',
    'forensics.legalAdvice': 'Rechtsberatung',
    'forensics.legalDesc': 'Fachkundige Unterstutzung in Gerichtsfallen im Zusammenhang mit Computerkriminalitat.',
    'forensics.teamTitle': 'Spezialisiertes Team fur Gerichtliche IT-Gutachten',
    'forensics.teamText1': 'Unser Team aus IT-Gutachtern verfugt uber umfangreiche Erfahrung bei der Erstellung von Gutachten fur Gerichtsverfahren. Wir fuhren umfassende forensische Analysen digitaler Gerate durch, stellen Beweismittel wieder her und prasentieren Beweise mit voller rechtlicher Absicherung.',
    'forensics.teamText2': 'Wir arbeiten mit Anwalten, Gerichten und Sicherheitskraften zusammen und gewahrleisten jederzeit die Beweismittelkette sowie die Integritat digitaler Beweise.',
    'forensics.legalValidity': 'Rechtliche Gultigkeit',
    'forensics.certifiedExperts': 'Zertifizierte Experten',
    'forensics.technicalReports': 'Technische Berichte',
    
    // Scanner
    'scanner.title': 'SCHWACHSTELLEN-SCANNER',
    'scanner.subtitle': 'Analysieren Sie Ihre Website in Echtzeit und entdecken Sie potenzielle Sicherheitslucken',
    'scanner.scan': 'SCANNER',
    'scanner.scanning': 'Scan lauft...',
    'scanner.analyzing': 'Analyse von Ports, SSL-Zertifikaten, Sicherheits-Headern und haufigen Schwachstellen...',
    'scanner.criticalCount': 'Kritisch',
    'scanner.high': 'Hoch',
    'scanner.medium': 'Mittel',
    'scanner.low': 'Niedrig',
    'scanner.securityScore': 'Sicherheitsbewertung',
    'scanner.excellent': 'Ausgezeichnet - Keine Schwachstellen gefunden',
    'scanner.good': 'Gut - Wenige Schwachstellen erkannt',
    'scanner.regular': 'Mittelmassig - Aufmerksamkeit erforderlich',
    'scanner.criticalStatus': 'Kritisch - Sofortige Massnahmen erforderlich',
    'scanner.detected': 'Erkannte Schwachstellen',
    'scanner.recommendation': 'Empfehlung:',
    'scanner.needHelp': 'Benotigen Sie Hilfe bei der Behebung dieser Schwachstellen?',
    'scanner.helpText': 'Unser Expertenteam kann Ihnen helfen, Ihre Website zu schutzen',
    'scanner.contactNow': 'JETZT KONTAKTIEREN',
    'scanner.inputPlaceholder': 'https://beispiel.com',
    'scanner.severity.critical': 'KRITISCH',
    'scanner.severity.high': 'HOCH',
    'scanner.severity.medium': 'MITTEL',
    'scanner.severity.low': 'NIEDRIG',
    'scanner.mock.sqli.type': 'SQL-Injection',
    'scanner.mock.sqli.description': 'Im Login-Formular wurde eine SQL-Injection-Schwachstelle erkannt.',
    'scanner.mock.sqli.recommendation': 'Prepared Statements und Eingabevalidierung implementieren.',
    'scanner.mock.xss.type': 'XSS (Cross-Site Scripting)',
    'scanner.mock.xss.description': 'Mogliche XSS-Schwachstelle in Kommentarfeldern.',
    'scanner.mock.xss.recommendation': 'Alle benutzergenerierten Inhalte bereinigen und escapen.',
    'scanner.mock.ssl.type': 'Schwaches SSL/TLS',
    'scanner.mock.ssl.description': 'Das SSL-Zertifikat verwendet veraltete Protokolle.',
    'scanner.mock.ssl.recommendation': 'Auf TLS 1.3 aktualisieren und altere Versionen deaktivieren.',
    'scanner.mock.headers.type': 'Sicherheits-Header',
    'scanner.mock.headers.description': 'Wichtige Sicherheits-Header fehlen (CSP, X-Frame-Options).',
    'scanner.mock.headers.recommendation': 'Geeignete HTTP-Sicherheits-Header konfigurieren.',
    'scanner.mock.version.type': 'Offengelegte Softwareversion',
    'scanner.mock.version.description': 'Die Version des Webservers wird in HTTP-Antworten offengelegt.',
    'scanner.mock.version.recommendation': 'Versionsinformationen des Servers verbergen.',
    'scanner.mock.cookies.type': 'Cookies Ohne Secure-Flag',
    'scanner.mock.cookies.description': 'Cookies enthalten die Flags Secure und HttpOnly nicht.',
    'scanner.mock.cookies.recommendation': 'Cookies mit geeigneten Sicherheits-Flags konfigurieren.',
    
    // Compliance
    'compliance.label': 'REGULATORISCHE KONFORMITAT',
    'compliance.title': 'Einhaltung von Vorschriften und Sicherheitsstandards',
    'compliance.subtitle': 'Wir gewahrleisten die Einhaltung der wichtigsten Cybersicherheits- und Datenschutzvorschriften sowie Standards auf nationaler und internationaler Ebene.',
    'compliance.auditTitle': 'Konformitatsaudits und Zertifizierungen',
    'compliance.auditText': 'Wir bieten Audit- und Beratungsleistungen an, um sicherzustellen, dass Ihre Organisation alle geltenden Vorschriften einhalt. Unser Expertenteam begleitet Sie durch den Zertifizierungsprozess und die Aufrechterhaltung der Konformitat.',
    'compliance.requestAudit': 'AUDIT ANFORDERN',
    'compliance.rgpd.subtitle': 'Datenschutz-Grundverordnung',
    'compliance.rgpd.description': 'Volle Einhaltung der DSGVO (EU) 2016/679 fur den Schutz personenbezogener Daten und der Privatsphare in der Europaischen Union.',
    'compliance.lopdgdd.subtitle': 'Organisches Datenschutzgesetz',
    'compliance.lopdgdd.description': 'Anpassung an das Organische Gesetz 3/2018 zum Schutz personenbezogener Daten und zur Gewahrleistung digitaler Rechte in Spanien.',
    'compliance.ens.subtitle': 'Nationales Sicherheitskonzept',
    'compliance.ens.description': 'Einhaltung des Koniglichen Dekrets 3/2010 des Nationalen Sicherheitskonzepts fur Informationssysteme im offentlichen Sektor.',
    'compliance.iso27001.subtitle': 'Informationssicherheitsmanagement',
    'compliance.iso27001.description': 'Implementierung von Managementsystemen fur Informationssicherheit gemass internationalen ISO/IEC 27001-Standards.',
    'compliance.nis2.subtitle': 'Netz- und Informationssicherheitsrichtlinie',
    'compliance.nis2.description': 'Vorbereitung auf die NIS2-Richtlinie (EU) 2022/2555 zu Cybersicherheitsmassnahmen in Netz- und Informationssystemen.',
    'compliance.lssi.subtitle': 'Gesetz uber Dienste der Informationsgesellschaft',
    'compliance.lssi.description': 'Einhaltung des Gesetzes 34/2002 uber Dienste der Informationsgesellschaft und den elektronischen Handel.',
    
    // Why Choose Us
    'why.label': 'WARUM UNS WAHLEN',
    'why.title': 'Wir sind Ihr vertrauenswurdiger Partner fur Cybersicherheit und IT',
    'why.subtitle': 'Cyberlabforensics bietet geschafskritische Dienstleistungen zur Erkennung, Reaktion und Bewaltigung von Cyberangriffen und uberwacht Sicherheitsherausforderungen rund um die Uhr.',
    'why.blueTeam': 'Blue-Team',
    'why.blueDesc': 'Proaktive Verteidigung und kontinuierliche Uberwachung Ihrer Infrastruktur.',
    'why.redTeam': 'Red-Team',
    'why.redDesc': 'Simulation realer Angriffe zur Starkung Ihrer Abwehr.',
    'why.incidentResponse': 'Incident Response',
    'why.incidentDesc': 'Spezialisiertes Team, das rund um die Uhr fur die Bearbeitung von Vorfallen verfugbar ist.',
    'why.training': 'Schulung und Sensibilisierung',
    'why.trainingDesc': 'Kontinuierliche Schulung Ihres Teams zu Best Practices der Sicherheit.',
    
    // SOC
    'soc.title': 'SOC - Sicherheitsoperationszentrum',
    'soc.cybersecurity': 'Cybersicherheit',
    'soc.riskAssessment': 'Risikobewertung',
    'soc.networkSecurity': 'Netzwerksicherheit',
    'soc.serverMonitoring': 'Serveruberwachung',
    'soc.emailProtection': 'E-Mail-Schutz',
    'soc.backup': 'Backup und Wiederherstellung',
    
    // CTA
    'cta.title': 'Bereit fur die beste Cybersicherheits-Erfahrung?',
    'cta.subtitle': 'Wir sind sicher, dass Sie mit unseren Dienstleistungen zu 100% zufrieden sein werden!',
    'cta.contact': 'KONTAKT',
    
    // Footer
    'footer.description': 'Professionelle Cybersicherheitslosungen zum Schutz Ihres Unternehmens.',
    'footer.quickLinks': 'Schnelllinks',
    'footer.legal': 'Rechtliches',
    'footer.legalNotice': 'Impressum',
    'footer.privacy': 'Datenschutzerklarung',
    'footer.cookies': 'Cookie-Richtlinie',
    'footer.terms': 'Allgemeine Geschaftsbedingungen',
    'footer.contactInfo': 'Kontaktinformationen',
    'footer.address': 'GEBAUDE GARAJE 2.0 - C. Sta. Cristina, Buro S1, 10195 Caceres',
    'footer.hours': 'Offnungszeiten: 09:00 - 20:00',
    'footer.rights': 'Alle Rechte vorbehalten.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}